### ISSUE TITLE
Dataframe equality ignoring schema

### ISSUE THREAD

**Issue by arunvelsriram** [MrPowers/chispa#31] opened 2021-06-28 16:45 UTC
Sometimes we just need to check if two dataframes have equal values irrespective of their schemas. How about introducing an argument `ignore_schema` to skip schema check?

https://github.com/MrPowers/chispa/blob/main/chispa/dataframe_comparer.py#L23

**Comment by aemorina** [comment] 2021-09-01 21:12
This would be a great feature. It may sound counterintuitive to want to compare two dataframes but it comes up often.

For example,  if I want to compare data read from a blob file and data from a database table the read statements will often times infer the schemas differently. It is a pain having to mainly define the schemas just so the assert statement will pass.

Would love to see this feature merged.

**Comment by arunvelsriram** [comment] 2021-09-15 18:30
@MrPowers would you like to share your thoughts on this?

**Comment by backtrackbaba** [comment] 2022-02-21 07:02
@MrPowers Any updates on this? Seems to be pretty useful

**Closed** 2022-02-21 19:38 UTC

**Comment by MrPowers** [comment] 2022-02-21 19:41
I merged this, thanks for the contribution.  Try out v0.9.2 and let me know if it works as intended.  Thanks!
